[libraries]

lib.files = [
"cpre381-toolflow/proj/test/tb_reg_file.vhd",
"cpre381-toolflow/proj/test/tb_onescomp.vhd",
"cpre381-toolflow/proj/test/tb_n_reg.vhd",
"cpre381-toolflow/proj/test/tb_n_adder.vhd",
"cpre381-toolflow/proj/test/tb_mux_32.vhd",
"cpre381-toolflow/proj/test/tb_mux2t1_df_2.vhd",
"cpre381-toolflow/proj/test/tb_mux2t1_N.vhd",
"cpre381-toolflow/proj/test/tb_mux2t1.vhd",
"cpre381-toolflow/proj/test/tb_fetch_logic.vhd",
"cpre381-toolflow/proj/test/tb_extenders.vhd",
"cpre381-toolflow/proj/test/tb_decoder_32.vhd",
"cpre381-toolflow/proj/test/tb_control_logic.vhd",
"cpre381-toolflow/proj/test/tb_alu_control.vhd",
"cpre381-toolflow/proj/test/tb_alu.vhd",
"cpre381-toolflow/proj/test/tb_add_sub.vhd",
"cpre381-toolflow/proj/test/tb_Shifter.vhd",
"cpre381-toolflow/proj/src/add_sub.vhd",
"cpre381-toolflow/proj/src/MIPS_types.vhd",
"cpre381-toolflow/internal/testpy/tb.vhd",
"cpre381-toolflow/proj/src/TopLevel/mem.vhd",
"cpre381-toolflow/proj/src/TopLevel/MIPS_Processor.vhd",
"cpre381-toolflow/proj/src/RegFile/reg_file.vhd",
"cpre381-toolflow/proj/src/RegFile/n_reg.vhd",
"cpre381-toolflow/proj/src/Provided Components/xorg2.vhd",
"cpre381-toolflow/proj/src/Provided Components/org2.vhd",
"cpre381-toolflow/proj/src/Provided Components/invg.vhd",
"cpre381-toolflow/proj/src/Provided Components/dffg.vhd",
"cpre381-toolflow/proj/src/Provided Components/andg2.vhd",
"cpre381-toolflow/proj/src/Provided Components/adder.vhd",
"cpre381-toolflow/proj/src/PipelineRegisters/WB_Reg.vhd",
"cpre381-toolflow/proj/src/PipelineRegisters/MEM_WB_reg.vhd",
"cpre381-toolflow/proj/src/PipelineRegisters/MEM_Reg.vhd",
"cpre381-toolflow/proj/src/PipelineRegisters/IF_ID_Reg.vhd",
"cpre381-toolflow/proj/src/PipelineRegisters/ID_EX_Reg.vhd",
"cpre381-toolflow/proj/src/PipelineRegisters/EX_Reg.vhd",
"cpre381-toolflow/proj/src/PipelineRegisters/EX_MEM_Reg.vhd",
"cpre381-toolflow/proj/src/Muxes/mux2t1_N.vhd",
"cpre381-toolflow/proj/src/Muxes/mux2t1_5.vhd",
"cpre381-toolflow/proj/src/Muxes/mux2t1.vhd",
"cpre381-toolflow/proj/src/Muxes/32t1_mux_32.vhd",
"cpre381-toolflow/proj/src/FetchLogic/fetch_logic.vhd",
"cpre381-toolflow/proj/src/ControlFlow/control_logic.vhd",
"cpre381-toolflow/proj/src/Basic Components/n-adder.vhd",
"cpre381-toolflow/proj/src/Basic Components/extenders.vhd",
"cpre381-toolflow/proj/src/Basic Components/Shifter.vhd",
"cpre381-toolflow/proj/src/Basic Components/OnesComp.vhd",
"cpre381-toolflow/proj/src/Basic Components/Decoder_32.vhd",
"cpre381-toolflow/proj/src/ALU/alu_control.vhd",
"cpre381-toolflow/proj/src/ALU/alu.vhd",
]
